### PR TITLE
Merge package:ffigen into dart-lang/native

### PR DESCRIPTION
**Pull request by liamappelbe**
*Do NOT squash merge!*

Fixes https://github.com/dart-lang/ffigen/issues/635

Following the steps from https://github.com/dart-lang/tools/pull/100

Current step:

13. Create a pull request and get it reviewed. Do not submit through the github UI, since it does not allow a fast forward merge. If there are changes required, back out and start over (it's OK to force push to the PR branch)

We decided to defer this step until a follow up PR, to make it easier to review:

6. Replace paths and links in files
    1. Badges: `https://github.com/dart-lang/ffigen/actions/workflows/test-package.yml` -> `https://github.com/dart-lang/native/actions/workflows/ffigen.yml`
    1. Remaining links, manually check if this does the right thing, otherwise insert steps above this step. `https://github.com/dart-lang/ffigen` -> `https://github.com/dart-lang/native/tree/main/pkgs/ffigen`

Steps to do:

14. Disable squash-only in GitHub settings, and merge with a fast forward merge to the main branch, enable squash-only in GitHub settings.
15. Push tags to github
16. Follow up with a PR adding links to the top-level readme table.
17. Add a commit to https://github.com/dart-lang/ffigen/ with it's readme pointing to this repo
18. Archive https://github.com/dart-lang/ffigen/.

## Renamed tags

 * [new tag]         ffigen-v7.2.11     -> ffigen-v7.2.11
 * [new tag]         ffigen-v5.0.0      -> ffigen-v5.0.0
 * [new tag]         ffigen-v5.0.1      -> ffigen-v5.0.1
 * [new tag]         ffigen-v6.0.0      -> ffigen-v6.0.0
 * [new tag]         ffigen-v6.0.1      -> ffigen-v6.0.1
 * [new tag]         ffigen-v6.0.2      -> ffigen-v6.0.2
 * [new tag]         ffigen-v6.1.0      -> ffigen-v6.1.0
 * [new tag]         ffigen-v6.1.1      -> ffigen-v6.1.1
 * [new tag]         ffigen-v6.1.2      -> ffigen-v6.1.2
 * [new tag]         ffigen-v7.0.0      -> ffigen-v7.0.0
 * [new tag]         ffigen-v7.1.0      -> ffigen-v7.1.0
 * [new tag]         ffigen-v7.2.0      -> ffigen-v7.2.0
 * [new tag]         ffigen-v7.2.1      -> ffigen-v7.2.1
 * [new tag]         ffigen-v7.2.10     -> ffigen-v7.2.10
 * [new tag]         ffigen-v7.2.2      -> ffigen-v7.2.2
 * [new tag]         ffigen-v7.2.3      -> ffigen-v7.2.3
 * [new tag]         ffigen-v7.2.4      -> ffigen-v7.2.4
 * [new tag]         ffigen-v7.2.5      -> ffigen-v7.2.5
 * [new tag]         ffigen-v7.2.6      -> ffigen-v7.2.6
 * [new tag]         ffigen-v7.2.7      -> ffigen-v7.2.7
 * [new tag]         ffigen-v7.2.8      -> ffigen-v7.2.8
 * [new tag]         ffigen-v7.2.9      -> ffigen-v7.2.9
 * [new tag]         ffigen-v8.0.0      -> ffigen-v8.0.0
 * [new tag]         ffigen-v8.0.0-dev.0 -> ffigen-v8.0.0-dev.0
 * [new tag]         ffigen-v8.0.0-dev.1 -> ffigen-v8.0.0-dev.1
 * [new tag]         ffigen-v8.0.0-dev.2 -> ffigen-v8.0.0-dev.2
 * [new tag]         ffigen-v8.0.0-dev.3 -> ffigen-v8.0.0-dev.3
 * [new tag]         ffigen-v8.0.1      -> ffigen-v8.0.1
 * [new tag]         ffigen-v8.0.2      -> ffigen-v8.0.2
 * [new tag]         ffigen-v9.0.0      -> ffigen-v9.0.0
 * [new tag]         ffigen-v9.0.1      -> ffigen-v9.0.1

### CODE REVIEW

**Comment by dcharkes** [comment]
Thanks @liamappelbe!

It looks like the coverage configuration and the changelog need to be updated, see redness on the bots.

**Comment by mit-mit** [comment]
After this lands, please also update the table https://github.com/dart-lang/native/blob/main/README.md#packages

**Comment by devoncarew** [comment]
> _Do NOT squash merge!_

@dcharkes - I believe you have sufficient permissions for this repo to temporarily enable 'Allow rebase merging', merge this PR, and then disable rebase merging.  Let me know if this is not the case -

**Comment by dcharkes** [comment]
> > _Do NOT squash merge!_
> 
> @dcharkes - I believe you have sufficient permissions for this repo to temporarily enable 'Allow rebase merging', merge this PR, and then disable rebase merging. Let me know if this is not the case -

I do indeed.

(But we'll have to address the redness on coverage and the publishing bot first.)

**Comment by liamappelbe** [comment]
Not sure what to do about this error. Seems like this validator doesn't understand dev versions. Unless someone has a workaround, we'll have to wait to merge the repos until after SDK 3.2 is published.

```
  Resolving dependencies...
  The current Dart SDK version is 3.1.5.
  
  Because ffigen requires SDK version >=3.2.0-114.0.dev <4.0.0, version solving failed.
```

**Comment by dcharkes** [comment]
@liamappelbe try setting the channel to beta in .github/workflows/publish.yaml (and update FFIgen to beta instead of dev). docs: https://github.com/dart-lang/ecosystem/blob/main/.github/workflows/publish.yaml#L60-L67

**Comment by liamappelbe** [comment]
@dcharkes Fixed the publish bot. PTAL

**Comment by dcharkes** [comment]
> @dcharkes Fixed the publish bot. PTAL

Nice! Both the publisher and code coverage tool is happy!

Regarding CLA bot, the two non-signed CLAs are ex Googlers who contributed during their time at Google, so these should be fine. Please submit an exception request following the link to the bot.

Before I manually merge, as we can only do this once, and commits are not squashed:

* Can we land some required changes on the FFIgen repo first? (e.g. the fix Dart formatting+beta SDK, and the fix markdown formatting)
* Should we consider also prefixing all commits with `[ffigen] `? `--commit-callback` [some examples](https://stackoverflow.com/questions/14332551/whats-the-fastest-way-to-edit-hundreds-of-git-commit-messages).
* Can we squash the commits that have not been merged into the FFIgen repo before the merge commit and the ones after the merge commit into one commit? (or one commit before and one after)? Also please write detailed commit messages on these, they will be in our history forever.
* Smaller nit:
  * Can we delete pkgs/ffigen/.github/workflows/test-package.yaml in the same commit as adding ./github/workflows/ffigen.yaml
* Merge with the last commit in dart-lang/native

**Comment by liamappelbe** [comment]
@dcharkes Ok, done. Should be good to go now. It's Friday afternoon here, so feel free to merge this during my weekend if it looks good.

**Comment by dcharkes** [comment]
The urls don't look correct: `https://github.com/dart-lang/native/tree/main/pkgs/ffigen/blob/main/test/native_test/native_test.dart` should be `https://github.com/dart-lang/native/tree/main/pkgs/ffigen/test/native_test/native_test.dart`.

`https://github.com/dart-lang/native/tree/main/pkgs/ffigen/issues/386` we can only rewrite the URLs for issues after we have migrated the issues. Though it might be that the old URLs for issues will still work, so in that case we can just keep the old URLs and let GitHub just forward to the migrated issue.

`https://github.com/dart-lang/native/tree/main/pkgs/ffigen/pull/402#issuecomment-1154348670` This should definitely stay the old URL.

Also, can we do the README header rewrite and the SDK to beta bump as a PR on the FFIgen repo first? That means less reviewing on the commits manually.

> It's Friday afternoon here, so feel free to merge this during my weekend if it looks good.

I'd rather do it on Monday, who knows we might miss something and need to do some cleanup. 🙄 

At least we need to transfer all issues, issue labels, label the issues with package:ffigen etc. (I can't find anything on transfering all issues to another repo at the same time. So we're going to have to hit "transfer issue" 85 times manually. Unless, @devoncarew knows some magic?)

**Comment by parlough** [comment]
> At least we need to transfer all issues, issue labels, label the issues with package:ffigen etc. (I can't find anything on transfering all issues to another repo at the same time. So we're going to have to hit "transfer issue" 85 times manually.)


Devon does have some magic prepared. The [repo_manage](https://github.com/dart-lang/ecosystem/tree/main/pkgs/repo_manage) tool has a `transfer-issues` bulk transfer command that can [add a specific label](https://github.com/dart-lang/ecosystem/blob/dda788671e943525b7393f7e2430de38e73c03dc/pkgs/repo_manage/lib/issue_transfer.dart#L40) if desired.

**Comment by devoncarew** [comment]
> > At least we need to transfer all issues, issue labels, label the issues with package:ffigen etc. (I can't find anything on transfering all issues to another repo at the same time. So we're going to have to hit "transfer issue" 85 times manually. Unless, devoncarew knows some magic?)
> 
> Devon does have some magic prepared. The [repo_manage](https://github.com/dart-lang/ecosystem/tree/main/pkgs/repo_manage) tool has a `transfer-issues` bulk transfer command that can [add a specific label](https://github.com/dart-lang/ecosystem/blob/dda788671e943525b7393f7e2430de38e73c03dc/pkgs/repo_manage/lib/issue_transfer.dart#L40) if desired.

Yup, from memory , there are a few ways to x-fer issues in bulk. Moritz wrote the one in the repo_manage tool. I believe he said that it would occasionally fail after some number of issues, but that that was harmless? You can you capture more of the moves w/ a subsequent run.

You definitely do want to have an additional label to help categorize the issues.

**Comment by liamappelbe** [comment]
@dcharkes PTAL

**Review by dcharkes — APPROVED** [review]

**Pull request merged**
