### PR TITLE
Correctly escape comments that may contain tags

### PR DESCRIPTION
**Pull request by brianquinlan**
Fixes https://github.com/dart-lang/native/issues/1408

- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Review by dcharkes — APPROVED** [review]

**Comment by dcharkes** [comment]
Thanks @brianquinlan!

I believe auto publishing doesn't work for packages that require the Flutter SDK. So this requires a manual merge (with red publish bot), and subsequently a manual `flutter pub publish`.

Hossein is on holiday this week. If this is important for you @brianquinlan, I can publish a new version with this change. Otherwise, it'll happen next week.

**Comment by brianquinlan** [comment]
I suspect that the `test_jnigen` failures are unrelated to my changes since the same tests pass on macOS and Windows:

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Note: javadoc: Loading source file example/in_app_java/android/app/src/main/java/com/example/in_app_java/AndroidUtils.java...
Note: javadoc: Loading source file /home/runner/.gradle/caches/modules-2/files-2.1/androidx.emoji2/emoji2/1.3.0/788179fcab96cd6ec9a3e284e2a509545dc0fb8d/emoji2-1.3.0-sources.jar/androidx/emoji2/text/EmojiCompat.java...
Note: javadoc: Loading source file /home/runner/.gradle/caches/modules-2/files-2.1/androidx.emoji2/emoji2/1.3.0/788179fcab96cd6ec9a3e284e2a509545dc0fb8d/emoji2-1.3.0-sources.jar/androidx/emoji2/text/DefaultEmojiCompatConfig.java...
/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-android/1.7.1/d43e33a7c7ee4bdb6fb3210bfdffee23f275e3dc/kotlinx-coroutines-android-1.7.1-sources.jar(/module-info.java):5: error: module not found: kotlin.stdlib
    requires kotlin.stdlib;
                   ^
/home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-android/1.7.1/d43e33a7c7ee4bdb6fb3210bfdffee23f275e3dc/kotlinx-coroutines-android-1.7.1-sources.jar(/module-info.java):6: error: module not found: kotlinx.coroutines.core
    requires kotlinx.coroutines.core;
                               ^
error: cannot access kotlinx.coroutines.android.module-info
  cannot resolve modules
Note: javadoc: 3 errors
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:497)
	at java.base/java.util.HashMap.putAll(HashMap.java:781)
	at com.github.dart_lang.jnigen.apisummarizer.Main.main(Main.java:132)

Fatal: Cannot generate summary: FormatException: Unexpected end of input (at character 1)

^

Error: Process completed with exit code 1.
```

> Hossein is on holiday this week. If this is important for you @brianquinlan, I can publish a new version with this change. Otherwise, it'll happen next week.

@dcharkes The CI for `package:http` is currently broken because the `jnigen`ed sources are not compatible with the `unintended_html_in_doc_comment` lint. Regenerating the sources would be the easiest path to a fix for us.

If doing a release is easy and low-risk, could you do one please?

**Comment by dcharkes** [comment]
> @dcharkes The CI for `package:http` is currently broken because the `jnigen`ed sources are not compatible with the `unintended_html_in_doc_comment` lint. Regenerating the sources would be the easiest path to a fix for us.

Maybe you can ignore the lint in the generated file for now?

> If doing a release is easy and low-risk, could you do one please?

I believe this knowledge is in @HosseinYousefi's brain. (We should document this @HosseinYousefi!)

**Comment by HosseinYousefi** [comment]
There is nothing worth documenting. 

You can safely release it if the CI is failing even without your change. I don't know why the CI fails, I'll investigate when I get back.

**Comment by brianquinlan** [comment]
> There is nothing worth documenting.
> 
> You can safely release it if the CI is failing even without your change. I don't know why the CI fails, I'll investigate when I get back.

So we just have to `flutter pub publish`? On a clean `master`?

**Comment by brianquinlan** [comment]
Maybe it is still worth waiting for https://github.com/dart-lang/native/issues/1430 to be fixed

**Comment by HosseinYousefi** [comment]
> > There is nothing worth documenting.
> 
> > 
> 
> > You can safely release it if the CI is failing even without your change. I don't know why the CI fails, I'll investigate when I get back.
> 
> 
> 
> So we just have to `flutter pub publish`? On a clean `master`?

Yes. We don't have a separate "stable" branch.

**Pull request merged**
