### PR TITLE
[jnigen] Update AGP

### PR DESCRIPTION
**Pull request by HosseinYousefi**

### CODE REVIEW

**Comment by dcharkes** [comment]
High level question: Flutter went to a newer AGP, and now we do too, does this break package:jni for older flutters?

**Comment by HosseinYousefi** [comment]
> High level question: Flutter went to a newer AGP, and now we do too, does this break package:jni for older flutters?

We didn't update AGP of `package:jni` itself, only the examples that run on CI.

**Comment by dcharkes** [comment]
Ah nice! So this is basically kind of updating all generated boilerplate that would have been created by “flutter create”.

**Comment by HosseinYousefi** [comment]
> Ah nice! So this is basically kind of updating all generated boilerplate that would have been created by “flutter create”.

Exactly, jni's gradle is agnostic about the AGP, even the new required "namespace" parameter is set conditionally:

```groovy
if (project.android.hasProperty("namespace")) {
  namespace 'com.github.dart_lang.jni'
}
```

**Review by dcharkes — APPROVED** [review]

**Pull request merged**
