### PR TITLE
[jnigen] Switch to `package:dart_flutter_team_lints`

### PR DESCRIPTION
**Pull request by dcharkes**
@HosseinYousefi You might want to enable the `strict-` analyzer options to ensure there's no bugs.

### CODE REVIEW

**Comment by dcharkes** [comment]
I'm not sure why the lints didn't show up locally, but this PR requires some more migration.

**Comment by HosseinYousefi** [comment]
I'll close this PR and open one myself then as most of the lints are todo.

**Comment by dcharkes** [comment]
Uh, you might want to address the separate lints in separate PRs, there are 1500 violations.

**Review by HosseinYousefi — APPROVED** [review]
LGTM!

**Pull request merged**
