### PR TITLE
Publish `0.5.4`

### PR DESCRIPTION
**Pull request by mosuem**
.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by dcharkes** [comment]
What are the API leaks? Did we start exporting something we didn’t before?

**Comment by dcharkes** [comment]
https://github.com/dart-lang/native/commits/main/pkgs/native_toolchain_c Looks like we didn’t actually change anything.

**Comment by mosuem** [comment]
> What are the API leaks? Did we start exporting something we didn’t before?

Could be `LinkerOptions.isClangLikeLinker`. I will move it somewhere else.

**Review by dcharkes — APPROVED** [review]

**Comment by dcharkes** [comment]
> > What are the API leaks? Did we start exporting something we didn’t before?
> 
> Could be `LinkerOptions.isClangLikeLinker`. I will move it somewhere else.

Does the API tool not run on publish_to none? Or why did we not see this before?

**Comment by mosuem** [comment]
> Does the API tool not run on publish_to none? Or why did we not see this before?

It does. I did add the leaking check kind of recently - maybe it was not there at the time.

**Comment by dcharkes** [comment]
Seems like that check is doing it’s job 🤓

**Pull request merged**
