### PR TITLE
Prepare to publish ffigen 14.0.0 and objective_c 2.0.0

### PR DESCRIPTION
**Pull request by liamappelbe**

### CODE REVIEW

**Comment by liamappelbe** [comment]
Publish check is failing because of the usual flutter/dart pub issue. I've verified both packages dry-run publish locally without any errors/warnings.

**Review by dcharkes — APPROVED** [review]

**Comment by dcharkes** [comment]
@liamappelbe  Please don't auto merge next time. Merge manually and immediately publish from locally. Now the publisher bot is red for all other PRs.

**Comment by liamappelbe** [comment]
I'll publish now.

**Comment by dcharkes** [comment]
> I'll publish now.

TYVM!

**Pull request merged**
