### PR TITLE
Ensure the NativeAssetsBuildRunner.link() produces a BuildResult with all assets

### PR DESCRIPTION
**Pull request by mkustermann**
Before this change a bundling tool would

  * call `buildResult = nativeAssetsBuildRunner.build(...)`
  * call `linkResult = nativeAssetsBuildRunner.link(buildResult: buildResult, ...)
  * get all assets via `allAssets = [...buildResult.assets, ...linkResult.assets]`

=> This PR makes the `link()` command produce a `LinkResult` containing
   all assets of the final application.

=> One could view this as the assets from `build()` without a linker to go to
   a default linker that just emits all of it's inputs.

=> This allows the `link()` step to also perform the application-wide
   validation steps (not just over all linker outputs but across build &
   link outputs)

Bundling tools now only have to deal with
  * `buildResult` in JIT mode (where linking is not enabled)
  * `linkResult` in AOT mode (where linking is enabled)

Instead of dealing with both `buildResult` and `linkResult` in AOT mode.

(In some sense one actually would prefer a `NativeAssetsBuilder.build` and
`NativeAssetsBuilder.buildAndLink` instead of the current API that exposes the
intermediary result from `build(linkingEnabled: true)` just to be explicitly
passed on to `link` later on)

### CODE REVIEW

**Comment by mkustermann** [comment]
Will update the tests & changelog

**Comment by dcharkes** [comment]
> (In some sense one actually would prefer a `NativeAssetsBuilder.build` and
> `NativeAssetsBuilder.buildAndLink` instead of the current API that exposes the
> intermediary result from `build(linkingEnabled: true)` just to be explicitly
> passed on to `link` later on)

Now that we don't actually run the build step before kernel compilation of the Dart code in any of the embedders (after I made kernel concatenation work for both JIT/AOT), we could actually do that. 👍

**Review by dcharkes — APPROVED** [review]

**Comment by mkustermann** [comment]
> Now that we don't actually run the build step before kernel compilation of the Dart code in any of the embedders (after I made kernel concatenation work for both JIT/AOT), we could actually do that. 👍

Yes, we could make that changes. Though if we ever allowed `hook/build.dart` to output dart code that is used to run/build the dart application, then we'd need the separation.

For now I'll just keep like this to not get too much off-trail (of making the system more flexible).

**Comment by mkustermann** [comment]
Thanks, @dcharkes !

**Pull request merged**
